apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm1-firewall
  namespace: ad-gomis-dev
  labels:
    role: firewall
    app: ad-gomis-dev
spec:
  runStrategy: Manual
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm1-firewall
    spec:
      domain:
        cpu:
          cores: 2
        memory:
          guest: 2Gi
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          containerDisk:
            image: quay.io/containerdisks/ubuntu:22.04
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              hostname: vm1-firewall
              user: admin
              users:
                - name: admin
                  sudo: ALL=(ALL) NOPASSWD:ALL
                  shell: /bin/bash
                  ssh_import_id:
                    - gh:ADONIS-IX
