apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: projet-3tiers

# Ordre de déploiement : namespace → réseaux → stockage → VMs
resources:
  - namespace.yaml
  - secrets/db-credentials.yaml
  - network/nad-lan.yaml
  - network/nad-dmz.yaml
  - vms/vm3-db.yaml       # VM3 en premier (stockage persistant)
  - vms/vm1-firewall.yaml
  - vms/vm2-web.yaml
  - services/svc-web.yaml

commonLabels:
  app: projet-3tiers
  env: tp
  managed-by: kustomize
