apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ad-gomis-dev

# Ordre de déploiement : namespace -> secret -> DB Pod -> VMs -> exposition Web
resources:
  - namespace.yaml
  - secrets/db-credentials.yaml
  - services/db-mysql.yaml
  - vms/vm1-firewall.yaml
  - vms/vm2-web.yaml
  - services/svc-web.yaml

commonLabels:
  app: ad-gomis-dev
  env: tp
  managed-by: kustomize
